export const ADD_POST = 'ADD_POST';
export const INIT_POSTS = 'INIT_POSTS';
export const POSTS_LOADED_START = 'POSTS_LOADED_START';
export const POSTS_LOADED_SUCCESS = 'POSTS_LOADED_SUCCESS';
export const POSTS_LOADED_FAILED = 'POSTS_LOADED_FAILED';

export const INIT_SUBMIT = 'INIT_SUBMIT';
export const POST_SUBMIT_START = 'POST_SUBMIT_START';
export const POST_SUBMIT_SUCCESS = 'POST_SUBMIT_SUCCESS';
export const POST_SUBMIT_FAILED = 'POST_SUBMIT_FAILED';